services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    network_mode: bridge
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped