openapi: 3.0.0
info:
  title: Mon API
  version: "1.0"

paths:
  /hello:
    get:
      operationId: app.hello
      responses:
        200:
          description: Message de bienvenue
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /echo:
    post:
      operationId: app.echo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Réponse écho
          content:
            application/json:
              schema:
                type: object